# Generated by Django 3.1.2 on 2020-10-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20201011_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
