# Generated by Django 3.1.2 on 2020-10-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20201023_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='custom_link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
