# Generated by Django 3.1.2 on 2020-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20201029_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='custom_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
