# Generated by Django 3.0.6 on 2020-10-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20201011_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
