name: Deploy Server
on:
  push:
    branches:
      - master
    paths-ignore: 'frontend/**/*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_SSH_HOST }}
          port: ${{ secrets.AWS_SERVER_SSH_PORT }}
          key: ${{ secrets.AWS_SERVER_SSH_PRIV_KEY }}
          username: ${{ secrets.AWS_SERVER_SSH_USER }}
          script: |
            whoami
            ls /home
            ls /home/ubuntu
            source ~/site/deploy.sh
